## Experiment 2

### Code 1

In [21]:
import numpy as np
# create a random 5x5 ndarray
X = np.random.randn(5, 5)
# make a mean and standard deviation
mean = X.mean()
std = X.std()
# normalize X
X_normalized = (X - mean) / std
np.save('X_normalized.npy', X_normalized)
# Output the values
print("Original Array X:\n", X)
print("\nMean of X:")
print(mean)
print("\nStandard Deviation of X:")
print(std)
print("\nNormalized Array X_normalized:\n", X_normalized)



Original Array X:
 [[ 0.96016258 -0.06793382 -0.33953773  2.43527592  0.10291982]
 [-0.76596373  0.07759943 -0.7680266   0.11267633  0.48648113]
 [-0.34660388 -1.21893098  0.75451275 -0.31950213  0.99370343]
 [ 0.84517443 -0.12240756 -1.05562648  1.23018082 -1.07738674]
 [ 0.60247132  0.76578091 -0.95516135 -1.23433332 -1.50317266]]

Mean of X:
-0.016305924178649782

Standard Deviation of X:
0.9345717406977287

Normalized Array X_normalized:
 [[ 1.0448299  -0.0552423  -0.34586089  2.62321418  0.1275726 ]
 [-0.80214046  0.10047956 -0.80434774  0.13801215  0.53798658]
 [-0.35342172 -1.2868194   0.82478277 -0.32442261  1.08071891]
 [ 0.92179157 -0.11352968 -1.11208216  1.33375181 -1.13536583]
 [ 0.6620971   0.83683981 -1.00458358 -1.30330005 -1.59096051]]


### Code 2

In [93]:
import numpy as np

# create a 10x10 ndarray with squares of the first 100 positive integers
squares = np.arange(1, 101).reshape(10, 10) ** 2

div_by_3 = squares[squares % 1 == 0]

# Print the result
print(squares)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
